name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Set up Git user info
        run: |
          git config --global user.email "bsiddhharth@gmail.com"
          git config --global user.name "bsiddhharth"
      - name: Pull latest changes from the remote
        run: git pull --rebase https://SID2702:$HF_TOKEN@huggingface.co/spaces/SID2702/Rag-Chat-Pdf-with-history main
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://SID2702:$HF_TOKEN@huggingface.co/spaces/SID2702/Rag-Chat-Pdf-with-history main
